# Generated by Django 3.1 on 2020-09-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка на видео')),
                ('file_id', models.CharField(max_length=200, verbose_name='Номер файла в телеграм')),
            ],
            options={
                'verbose_name': 'Ссылки',
                'verbose_name_plural': 'Ссылка',
            },
        ),
    ]
