# Generated by Django 3.1 on 2020-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='login')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('adress', models.CharField(max_length=500, verbose_name='adress')),
                ('promo', models.CharField(max_length=200, verbose_name='promo')),
                ('info', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
