# Generated by Django 3.1 on 2020-10-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'Ссылку', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
